### PR TITLE
Allow for specifying profiles.

### PR DESCRIPTION
**Pull request by nicksloan**
This one is much better, and has a neat benefit of actually working. Still not a node guy, so it still might suck.

### CODE REVIEW

**Comment by pracucci** [comment]
Hi Nick,
thanks for your contribution. Your changes look good to me. Is there any specific reason why you've closed the PR, or I can merge it?

Marco

**Comment by nicksloan** [comment]
@pracucci It had been a very long time with no activity. I'm not using this project anymore myself, so I wanted to clean up my GitHub account.

**Comment by nicksloan** [comment]
@pracucci Sadly, I've deleted the repository and I don't have a local copy, though it looks like the diffs and files are still visible. You might have to copy the contents of the file and manually merge it in. Sorry for the inconvenience.

**Comment by pracucci** [comment]
@nicksloan I didn't notice your PR was dated Apr 2015 (I never received the notification for that and never noticed it, since `gulp-aws` is a project we don't use anymore internally).

I will leave it closed and unmerged, since you don't need it anymore, but I will be happy to merge it if anyone will ask for it.

**Pull request closed without merging**
